version: "3"
services:
  data-consumer:
    image: ozgurclub/thermostat-data-consumer
    ports:
      - 8080:8076
    networks:
      - backend
    environment:
      - INFLUX_URL=http://influxdb:8086
      - MQTT_URL=tcp://mosquitto:1883
    links:
      - "mosquitto"
      - "influxdb"
  sensor1:
    image: ozgurclub/thermostat
    networks:
      - backend
    environment:
      - mqttClientConnectionString=tcp://mosquitto:1883
      - applicationId=sensor1
    links:
      - "mosquitto"
  sensor2:
    image: ozgurclub/thermostat
    networks:
      - backend
    environment:
      - mqttClientConnectionString=tcp://mosquitto:1883
      - applicationId=sensor2
    links:
      - "mosquitto"
  sensor3:
    image: ozgurclub/thermostat
    networks:
      - backend
    environment:
      - mqttClientConnectionString=tcp://mosquitto:1883
      - applicationId=sensor3
    links:
      - "mosquitto"
  mosquitto:
    image: eclipse-mosquitto:1.4.12
    container_name: mosquitto
    ports:
      - 1883:1883 # MQTT port
      - 9001:9001 # MQTT websocket port
    networks:
      - backend
    volumes:
      - $PWD/conf/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - $PWD/conf/mosquitto/data:/mosquitto/data

  influxdb:
    image: influxdb:1.5.2
    container_name: influxdb
    environment:
      - INFLUXDB_REPORTING_DISABLED=true
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=root
      - INFLUXDB_ADMIN_PASSWORD=root
      - INFLUXDB_DB=iotdata
    networks:
      - backend
    ports:
      - 8086:8086
    volumes:
      - $PWD/conf/influxdb/data:/var/lib/influxdb
networks:
  backend:
